name: 

on:
  workflow_dispatch: {}
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - ready_for_review
    branches:
      - develop
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.feature-branching.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: JonDotsoy/feature-branching@v2.0.1-preview.2
        id: feature-branching
        with:
          base_brach: develop
          label_name_to_merge: next-feature
          merge_strategy: ours
        env:
          GH_TOKEN: ${{ github.token }}
      - run: |
          echo Last feature-branching.outputs.ref	: ${{ steps.feature-branching.outputs.ref	 }}
      - run: |
          echo Last feature-branching.outputs.changed: ${{ steps.feature-branching.outputs.changed }}
      - run: |
          echo Last feature-branching.outputs.pr_name: ${{ steps.feature-branching.outputs.pr_name }}

  say_hello:
    needs: merge
    if: needs.merge.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
